name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repository structure
        run: |
          pwd
          find . -type f \( -name "*.csproj" -o -name "*.sln" -o -name "*.slnx" \)

      - name: Restore
        run: dotnet restore DemoApps/DemoApps/DemoApps.csproj

      - name: Build
        run: dotnet build DemoApps/DemoApps/DemoApps.csproj -c Release

      - name: Publish
        run: dotnet publish DemoApps/DemoApps/DemoApps.csproj -c Release -o /var/www/DemoApps

      - name: Restart Service
        run: |
          sudo systemctl restart DemoApps

      - name: Verify
        run: |
          sudo systemctl status DemoApps --no-pager